using HaPcRemote.Service.Models;
using ValveKeyValue;

namespace HaPcRemote.Service.Services;

public class SteamService(ISteamPlatform platform) : ISteamService
{
    private List<SteamGame>? _cachedGames;
    private DateTime _cacheExpiry;
    private static readonly TimeSpan CacheDuration = TimeSpan.FromHours(1);

    public async Task<List<SteamGame>> GetGamesAsync()
    {
        if (_cachedGames != null && DateTime.UtcNow < _cacheExpiry)
            return _cachedGames;

        var steamPath = platform.GetSteamPath();
        if (steamPath == null)
        {
            if (_cachedGames != null)
                return _cachedGames;

            throw new InvalidOperationException("Steam is not installed.");
        }

        var games = await Task.Run(() => LoadInstalledGames(steamPath));
        _cachedGames = games;
        _cacheExpiry = DateTime.UtcNow + CacheDuration;
        return games;
    }

    public async Task<SteamRunningGame?> GetRunningGameAsync()
    {
        var appId = platform.GetRunningAppId();
        if (appId == 0)
            return null;

        // Warm the cache if not yet populated
        if (_cachedGames == null || _cachedGames.Count == 0)
        {
            try { await GetGamesAsync(); }
            catch (InvalidOperationException) { /* Steam path unavailable, continue without cache */ }
        }

        var name = _cachedGames?.Find(g => g.AppId == appId)?.Name;

        // Game is running but not in the top-20 list — look it up from its manifest or shortcuts
        if (name == null)
        {
            var steamPath = platform.GetSteamPath();
            if (steamPath != null)
            {
                name = IsShortcutAppId(appId)
                    ? FindShortcutName(steamPath, appId)
                    : FindGameNameFromManifest(steamPath, appId);
            }
        }

        name ??= $"Unknown ({appId})";
        return new SteamRunningGame { AppId = appId, Name = name };
    }

    public async Task<SteamRunningGame?> LaunchGameAsync(int appId)
    {
        var runningAppId = platform.GetRunningAppId();
        if (runningAppId == appId)
            return await GetRunningGameAsync();

        if (runningAppId != 0)
            await StopGameAsync();

        // Non-Steam shortcuts use a shifted appid for the steam:// URI
        var launchId = IsShortcutAppId(appId)
            ? ((long)(uint)appId << 32) | 0x02000000
            : appId;

        platform.LaunchSteamUrl($"steam://rungameid/{launchId}");

        // Brief poll — Steam registers running state within seconds
        for (var i = 0; i < 10; i++)
        {
            await Task.Delay(500);
            var running = platform.GetRunningAppId();
            if (running == appId)
                return await GetRunningGameAsync();
        }

        return null; // Steam didn't accept the launch
    }

    public Task StopGameAsync()
    {
        var appId = platform.GetRunningAppId();
        if (appId == 0)
            return Task.CompletedTask;

        var steamPath = platform.GetSteamPath();
        if (steamPath == null)
            return Task.CompletedTask;

        var installDir = GetGameInstallDir(steamPath, appId);
        if (installDir != null)
            platform.KillProcessesInDirectory(installDir);

        return Task.CompletedTask;
    }

    /// <summary>
    /// Shortcut appids are generated by Steam from exe+appname and are always negative when
    /// stored as a signed 32-bit int (high bit set).
    /// </summary>
    internal static bool IsShortcutAppId(int appId) => appId < 0;

    // ── Static VDF parsers (testable without mocking) ────────────────

    internal static List<string> ParseLibraryFolders(string vdfContent)
    {
        var paths = new List<string>();
        using var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(vdfContent));
        var kv = KVSerializer.Create(KVSerializationFormat.KeyValues1Text);
        var data = kv.Deserialize(stream);

        foreach (var folder in data)
        {
            var path = folder["path"]?.ToString();
            if (!string.IsNullOrEmpty(path))
                paths.Add(path.Replace(@"\\", @"\"));
        }

        return paths;
    }

    internal static SteamGame? ParseAppManifest(string acfContent)
    {
        using var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(acfContent));
        var kv = KVSerializer.Create(KVSerializationFormat.KeyValues1Text);
        var data = kv.Deserialize(stream);

        var appIdStr = data["appid"]?.ToString();
        var name = data["name"]?.ToString();
        var lastPlayedStr = data["LastPlayed"]?.ToString();
        var lastUpdatedStr = data["LastUpdated"]?.ToString();

        if (string.IsNullOrEmpty(appIdStr) || string.IsNullOrEmpty(name))
            return null;

        if (!int.TryParse(appIdStr, out var appId))
            return null;

        // Prefer LastPlayed (actual play history); fall back to LastUpdated (install/update time)
        if (!long.TryParse(lastPlayedStr, out var lastPlayed))
            long.TryParse(lastUpdatedStr, out lastPlayed);

        return new SteamGame { AppId = appId, Name = name, LastPlayed = lastPlayed };
    }

    internal static string? ParseInstallDir(string acfContent)
    {
        using var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(acfContent));
        var kv = KVSerializer.Create(KVSerializationFormat.KeyValues1Text);
        var data = kv.Deserialize(stream);
        return data["installdir"]?.ToString();
    }

    internal static List<SteamGame> ParseShortcuts(Stream stream)
    {
        var shortcuts = new List<SteamGame>();
        var kv = KVSerializer.Create(KVSerializationFormat.KeyValues1Binary);
        KVObject root;
        try
        {
            root = kv.Deserialize(stream);
        }
        catch
        {
            return shortcuts;
        }

        foreach (var entry in root)
        {
            var appName = entry["AppName"]?.ToString()
                          ?? entry["appname"]?.ToString();
            if (string.IsNullOrEmpty(appName))
                continue;

            // Steam stores shortcut appid as a signed 32-bit int (high bit set).
            // Try appid first, then fallback to calculating from exe+appname.
            int appId;
            var appIdStr = entry["appid"]?.ToString();
            if (!string.IsNullOrEmpty(appIdStr) && int.TryParse(appIdStr, out var parsed) && parsed != 0)
            {
                appId = parsed;
            }
            else
            {
                // Fallback: generate the shortcut appid from exe + appname
                var exe = entry["Exe"]?.ToString() ?? entry["exe"]?.ToString() ?? "";
                appId = GenerateShortcutAppId(exe, appName);
            }

            var lastPlayedStr = entry["LastPlayTime"]?.ToString();
            long.TryParse(lastPlayedStr, out var lastPlayed);

            shortcuts.Add(new SteamGame
            {
                AppId = appId,
                Name = appName,
                LastPlayed = lastPlayed,
                IsShortcut = true
            });
        }

        return shortcuts;
    }

    /// <summary>
    /// Generates a non-Steam shortcut appid using the same CRC algorithm Steam uses.
    /// The result is always negative as a signed int32 (high bit set).
    /// </summary>
    internal static int GenerateShortcutAppId(string exe, string appName)
    {
        // Steam algorithm: CRC32(exe + appname) | 0x80000000
        var input = System.Text.Encoding.UTF8.GetBytes(exe + appName);
        var crc = Crc32(input);
        return (int)(crc | 0x80000000);
    }

    private static uint Crc32(byte[] data)
    {
        const uint polynomial = 0xEDB88320;
        var crc = 0xFFFFFFFF;
        foreach (var b in data)
        {
            crc ^= b;
            for (var i = 0; i < 8; i++)
                crc = (crc & 1) != 0 ? (crc >> 1) ^ polynomial : crc >> 1;
        }
        return crc ^ 0xFFFFFFFF;
    }

    private static string? FindGameNameFromManifest(string steamPath, int appId)
    {
        var libraryFoldersPath = Path.Combine(steamPath, "steamapps", "libraryfolders.vdf");
        if (!File.Exists(libraryFoldersPath))
            return null;

        var vdfContent = File.ReadAllText(libraryFoldersPath);
        var libraryPaths = ParseLibraryFolders(vdfContent);

        foreach (var libPath in libraryPaths)
        {
            var manifestPath = Path.Combine(libPath, "steamapps", $"appmanifest_{appId}.acf");
            if (!File.Exists(manifestPath))
                continue;

            try
            {
                var content = File.ReadAllText(manifestPath);
                var game = ParseAppManifest(content);
                if (game != null)
                    return game.Name;
            }
            catch
            {
                // Skip corrupt manifest
            }
        }

        return null;
    }

    private static string? FindShortcutName(string steamPath, int appId)
    {
        var shortcuts = LoadShortcuts(steamPath);
        return shortcuts.Find(s => s.AppId == appId)?.Name;
    }

    private static List<SteamGame> LoadInstalledGames(string steamPath)
    {
        var libraryFoldersPath = Path.Combine(steamPath, "steamapps", "libraryfolders.vdf");
        if (!File.Exists(libraryFoldersPath))
            return [];

        var vdfContent = File.ReadAllText(libraryFoldersPath);
        var libraryPaths = ParseLibraryFolders(vdfContent);

        var games = new List<SteamGame>();
        foreach (var libPath in libraryPaths)
        {
            var steamAppsDir = Path.Combine(libPath, "steamapps");
            if (!Directory.Exists(steamAppsDir))
                continue;

            foreach (var acfFile in Directory.EnumerateFiles(steamAppsDir, "appmanifest_*.acf"))
            {
                try
                {
                    var content = File.ReadAllText(acfFile);
                    var game = ParseAppManifest(content);
                    if (game != null)
                        games.Add(game);
                }
                catch
                {
                    // Skip corrupt manifests
                }
            }
        }

        // Discover non-Steam shortcuts from all userdata profiles
        var shortcuts = LoadShortcuts(steamPath);
        games.AddRange(shortcuts);

        return games
            .OrderByDescending(g => g.LastPlayed)
            .Take(20)
            .ToList();
    }

    private static List<SteamGame> LoadShortcuts(string steamPath)
    {
        var shortcuts = new List<SteamGame>();
        var userDataDir = Path.Combine(steamPath, "userdata");
        if (!Directory.Exists(userDataDir))
            return shortcuts;

        foreach (var userDir in Directory.EnumerateDirectories(userDataDir))
        {
            var shortcutsPath = Path.Combine(userDir, "config", "shortcuts.vdf");
            if (!File.Exists(shortcutsPath))
                continue;

            try
            {
                using var stream = File.OpenRead(shortcutsPath);
                var parsed = ParseShortcuts(stream);
                shortcuts.AddRange(parsed);
            }
            catch
            {
                // Skip corrupt shortcuts files
            }
        }

        // Deduplicate by AppId (same shortcut may appear under multiple Steam user profiles)
        return shortcuts
            .GroupBy(s => s.AppId)
            .Select(g => g.OrderByDescending(s => s.LastPlayed).First())
            .ToList();
    }

    private static string? GetGameInstallDir(string steamPath, int appId)
    {
        // Search all library folders, not just the main Steam path
        var libraryFoldersPath = Path.Combine(steamPath, "steamapps", "libraryfolders.vdf");
        if (!File.Exists(libraryFoldersPath))
            return null;

        var vdfContent = File.ReadAllText(libraryFoldersPath);
        var libraryPaths = ParseLibraryFolders(vdfContent);

        foreach (var libPath in libraryPaths)
        {
            var steamAppsDir = Path.Combine(libPath, "steamapps");
            var manifestPath = Path.Combine(steamAppsDir, $"appmanifest_{appId}.acf");

            if (!File.Exists(manifestPath))
                continue;

            var content = File.ReadAllText(manifestPath);
            var installDir = ParseInstallDir(content);

            if (!string.IsNullOrEmpty(installDir))
                return Path.Combine(steamAppsDir, "common", installDir);
        }

        return null;
    }
}
